# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
      env: 
        MONGO_URI: ${{ secrets.MONGO_URI }}
        
    - run: npm ci
    - run: cd backend
    - run: ls
    - run: echo $MONGO_URI
    - run: echo secrets.$MONGO_URI
    - run: echo $secrets.$MONGO_URI
    - run: echo ${{ secrets.$MONGO_URI }}
    - run: npm i
    - run: npm ci 
    - run: cd backend && npm i 
    # - run: npm start
    - run: cd ..
    # - run: export MONGO_URI="$MONGO_URI"
    - run: echo "$mongo_uri"
    - run: echo "$MONGO_URI"
    - run: npm run scrape:headless
